#pragma once
namespace tech
{
enum MONEY_TYPE
{
	MONEY_TYPE_INVALID=-1,
	MONEY_TYPE_DIAMOND,	//钻石
	MONEY_TYPE_COUNT,
};

enum PLAYER_ATTR
{
	PLAYER_ATTR_INVALID=-1,
	PLAYER_ATTR_LEVEL,					//等级
	PLAYER_ATTR_HOME_LEVEL,				//水晶等级
	PLAYER_ATTR_RMB,					//RMB
	PLAYER_ATTR_EXP,					//EXP
	PLAYER_ATTR_TOWER_A,				//塔A
	PLAYER_ATTR_VIP,					//VIP
	PLAYER_ATTR_VIP_MAX,				//VIP
	PLAYER_ATTR_VIGOR,					//体力
	PLAYER_ATTR_HONOR,					//荣誉
	PLAYER_ATTR_AGENCY,					//机构类型
	PLAYER_ATTR_GOLD,					//金币
	PLAYER_ATTR_ITEM_1,					//物品数量
	PLAYER_ATTR_ITEM_2,					//物品数量
	PLAYER_ATTR_ITEM_3,					//物品数量
	PLAYER_ATTR_ITEM_4,					//物品数量
	PLAYER_ATTR_ITEM_5,					//物品数量
	PLAYER_ATTR_NAME_BRAND,				//名牌数量
	PLAYER_ATTR_LOGIN_REWARD,			//登陆奖励领取进度
	PLAYER_ATTR_FIRST_RECHARGE_REWARD,	//首冲奖励是否领取
	PLAYER_ATTR_LEVEL_REWARD,			//等级奖励领取进度
	PLAYER_ATTR_RANK,					//当前排名
	PLAYER_ATTR_BEST_RANK,				//最佳排名
	PLAYER_ATTR_GUILD,					//guildID
	PLAYER_ATTR_COUNT,
};

enum PLAYER_ATTR64
{
	PLAYER_ATTR64_INVALID=-1,
	PLAYER_ATTR64_ACHIEVEMENT,	//成就
	PLAYER_ATTR64_CONTRIBUTION,	//贡献度
	PLAYER_ATTR64_ALL_SCORE,	//累计得分
	PLAYER_ATTR64_ALL_SCORE_1,	//累计得分1
	PLAYER_ATTR64_ALL_SCORE_2,	//累计得分2
	PLAYER_ATTR64_ALL_SCORE_3,	//累计得分3
	PLAYER_ATTR64_ALL_SCORE_4,	//累计得分4
	PLAYER_ATTR64_SUCCESS,		//胜利次数
	PLAYER_ATTR64_FAILURE,		//
	PLAYER_ATTR64_COUNT,
};

enum PLAYER_ATTR_TIME
{
	PLAYER_ATTR_TIME_INVALID=-1,
	PLAYER_ATTR_TIME_HOMT_TIME,				//水晶破坏事件
	PLAYER_ATTR_TIME_TOWER_A_TIME,			//塔A时间
	PLAYER_ATTR_TIME_LOGIN,					//登录时间
	PLAYER_ATTR_TIME_LOGOUT,				//退出时间
	PLAYER_ATTR_TIME_VIGOR_TIME,			//活力时间
	PLAYER_ATTR_TIME_PVP_OFFLINE_COOLDOWN,	//下次异步pvp的时间
	PLAYER_ATTR_TIME_PVP_CANDIDATE_COOLDOWN,//下次刷新对手的时间
	PLAYER_ATTR_TIME_COUNT,
};

enum PLAYER_ATTR_STRING
{
	PLAYER_ATTR_STRING_INVALID=-1,
	PLAYER_ATTR_STRING_ACCOUNT,	//账号名
	PLAYER_ATTR_STRING_NAME,	//玩家名
	PLAYER_ATTR_STRING_QQ,		//qq号
	PLAYER_ATTR_STRING_COUNT,
};

enum CARDS
{
	CARDS_INVALID=-1,
	CARDS_CARD_1,	//card1
	CARDS_CARD_2,	//card2
	CARDS_CARD_3,	//card3
	CARDS_CARD_4,	//card4
	CARDS_COUNT,
};

enum COUNTER_TYPE
{
	COUNTER_TYPE_INVALID=-1,
	COUNTER_TYPE_COUNT_1,	//午间已免费领取体力
	COUNTER_TYPE_COUNT_2,	//午间已免费领取体力
	COUNTER_TYPE_COUNT_3,	//午间已免费领取体力
	COUNTER_TYPE_COUNT_4,	//午间已免费领取体力
	COUNTER_TYPE_COUNT_5,	//午间已免费领取体力
	COUNTER_TYPE_COUNT_6,	//午间已免费领取体力
	COUNTER_TYPE_COUNT_7,	//午间已免费领取体力
	COUNTER_TYPE_COUNT_8,	//午间已免费领取体力
	COUNTER_TYPE_COUNT_9,	//午间已免费领取体力
	COUNTER_TYPE_COUNT_1_0,	//午间已免费领取体力
	COUNTER_TYPE_COUNT_1_1,	//午间已免费领取体力
	COUNTER_TYPE_COUNT_1_2,	//午间已免费领取体力
	COUNTER_TYPE_COUNT_1_3,	//午间已免费领取体力
	COUNTER_TYPE_COUNT_1_4,	//午间已免费领取体力
	COUNTER_TYPE_COUNT_1_5,	//午间已免费领取体力
	COUNTER_TYPE_COUNT,
};

enum COUNTER_TIME_TYPE
{
	COUNTER_TIME_TYPE_INVALID=-1,
	COUNTER_TIME_TYPE_TIME_1,	//午间已免费领取体力
	COUNTER_TIME_TYPE_TIME_2,	//午间已免费领取体力
	COUNTER_TIME_TYPE_TIME_3,	//午间已免费领取体力
	COUNTER_TIME_TYPE_TIME_4,	//午间已免费领取体力
	COUNTER_TIME_TYPE_TIME_5,	//午间已免费领取体力
	COUNTER_TIME_TYPE_TIME_6,	//午间已免费领取体力
	COUNTER_TIME_TYPE_TIME_7,	//午间已免费领取体力
	COUNTER_TIME_TYPE_TIME_8,	//午间已免费领取体力
	COUNTER_TIME_TYPE_TIME_9,	//午间已免费领取体力
	COUNTER_TIME_TYPE_TIME_1_0,	//午间已免费领取体力
	COUNTER_TIME_TYPE_TIME_1_1,	//午间已免费领取体力
	COUNTER_TIME_TYPE_TIME_1_2,	//午间已免费领取体力
	COUNTER_TIME_TYPE_TIME_1_3,	//午间已免费领取体力
	COUNTER_TIME_TYPE_TIME_1_4,	//午间已免费领取体力
	COUNTER_TIME_TYPE_TIME_1_5,	//午间已免费领取体力
	COUNTER_TIME_TYPE_COUNT,
};

enum COUNTER64_TYPE
{
	COUNTER64_TYPE_INVALID=-1,
	COUNTER64_TYPE_BIG_1,	//午间已免费领取体力
	COUNTER64_TYPE_BIG_2,	//午间已免费领取体力
	COUNTER64_TYPE_BIG_3,	//午间已免费领取体力
	COUNTER64_TYPE_BIG_4,	//午间已免费领取体力
	COUNTER64_TYPE_BIG_5,	//午间已免费领取体力
	COUNTER64_TYPE_BIG_6,	//午间已免费领取体力
	COUNTER64_TYPE_BIG_7,	//午间已免费领取体力
	COUNTER64_TYPE_BIG_8,	//午间已免费领取体力
	COUNTER64_TYPE_BIG_9,	//午间已免费领取体力
	COUNTER64_TYPE_BIG_1_0,	//午间已免费领取体力
	COUNTER64_TYPE_BIG_1_1,	//午间已免费领取体力
	COUNTER64_TYPE_BIG_1_2,	//午间已免费领取体力
	COUNTER64_TYPE_BIG_1_3,	//午间已免费领取体力
	COUNTER64_TYPE_BIG_1_4,	//午间已免费领取体力
	COUNTER64_TYPE_BIG_1_5,	//午间已免费领取体力
	COUNTER64_TYPE_COUNT,
};

enum INFOS
{
	INFOS_INVALID=-1,
	INFOS_INFO_1,	//注释1
	INFOS_INFO_2,	//注释2
	INFOS_INFO_3,	//注释3
	INFOS_INFO_4,	//注释4
	INFOS_INFO_5,	//注释5
	INFOS_INFO_6,	//注释6
	INFOS_INFO_7,	//注释7
	INFOS_COUNT,
};

}
