#ifndef __SERVER_PACKER_HEADER__
#define __SERVER_PACKER_HEADER__

namespace tech
{
	const int PROTOCOL_VERSION = 20150724;
	enum PACKET
	{
		PACKET_C2S_VERSION_INFO,		// 客户端发送来版本信息
		PACKET_S2C_SERVER_INFO,			// 获取服务器信息;


		PACKET_ERROR,				// 错误ID号.
		PACKET_SUCCESS,				// 成功包的id号.
		PACKET_PING,				// PING.
		PACKET_LOGIN,				// 角色登录.
		PACKET_LOGINRESULT,			// 登录返回.
		PACKET_CHANGE_INFO,			// 修改信息
		PACKET_CHANGE_INFO_RET,		// 修改信息回复;

		// 玩家属性.
		PACKET_SYNC_PLAYER_ATTR,	// 玩家基本属性;
		PACKET_SYNC_PLAYER_ATTR64,	// 玩家uint64类型的属性;
		PACKET_SYNC_PLAYER_STRINGS,	// 玩家字符串类型属性;
		PACKET_SYNC_PLAYER_TIME,	// 玩家时间类型属性;
		PACKET_SYNC_MONEY,			// 玩家属性uint64类型;money.
		PACKET_SYNC_EXTRA,			//PLAYER EXTRA DATA;
		PACKET_SAVE_ATTRS,			// 客户端需要保存到服务器的属性

		// 进入subject/version/grade/chapter/classindex.
		PACKET_ENTER_GAME_TYPE,
		PACKET_ENTER_GAME_RESULT,

		// PK相关.
		PACKET_ASK_PK_LIST,			// [请求进入pvp列表]	询问pk列表
		PACKET_CANCEL_PK_LIST,		// [请求离开pvp列表]	PK列表，有在线好友，先在线好友，否则在线玩家,要么说没匹配，后面做机器人.
		PACKET_ASKPK,				// [目前没用]			pk请求
		PACKET_ASKPKRESULT,			// [战斗开始]			pk请求结果.
		PACKET_LEAVEBATTLE,			// 中间离开战斗,比如自己先做完 先离开
		PACKET_QUESTION_BANK,		// [返回给客户端题库]								题库		
		PACKET_ANSWER,				// [客户端每回答一题提交的答案]						提交答案;
		PACKET_PKSTEP,				// [服务器广播给对方你是否答对,或者答对了多少个]	pk step.双方的回应通知;
		PACKET_PKEND,				// [时间到，发送总结果,后面定]						pk end.
		PACKET_ASK_USE_ITEM,		// [pk中使用道具]
		PACKET_BROADCAST_USEITEM,	// [使用道具后同步]
		
		
		// 普通答题
		PACKET_REPORT_RESULT,		// 普通答题结果通知到服务器端;
		PACKET_REPORT_RESULT_REWARD,// 奖励;
		
		// 物品相关.
		PACKET_SYNC_BAG,			// 发送item bag到客户端.
		PACKET_ASK_ITEM,			// 请求操作（根据类型看是否是删除，使用等等）
		PACKET_ITEM_RETURN,			// 物品操作返回类型,根据类型是否是删除,修改item信息等.

		//好友信息
		PACKET_ASK_FRIENDS,			// 询问qq好友.[安装了应用的并且在游戏中的qq好友].
		PACKET_SYNC_FRIEND,			// 发送好友信息;【注意我这边之保存的是客户端添加的QQ好友并且有这个应用的】
		PACKET_SYNC_FRIEND_END,		// 结束;
		PACKET_S2C_FRIEND_DATA,		// 好友信息的改变通知(名牌数量)
//		PACKET_FRIEND,				// 加,删除 好友.

		// 购买体力;
		PACKET_C2S_UPDATE_VIGOR,		// 体力更新标记;
		// 扣除体力
		PACKET_USE_VIGOR,			// c2s扣除体力;
		// 排行榜
		PACKET_QUERY_RANK,			// c2s请求排行榜信息
		PACKET_RANK_INFO,			// s2c排行榜

		// mial.
		PACKET_SYNC_MAIL,			// MAIL LIST
		PACKET_ADD_MAIL,			// ADD MAIL
		PACKET_DEL_MAIL,			// DEL MAIL
		PACKET_DEL_MAIL_RESULT,		// DEL RESULT.

		//使用物品
		PACKET_GET_ITEMS,			// get item and save to client local.
		//激活码领取活动;
		PACKET_C2S_ACTIVATION_CODE,		// 激活码验证;
		PACKET_S2C_ACTIVE_REWARD,	//奖励

		//撕名牌.
		PACKET_C2S_IN_NAMEBRAND,	// 进入
		PACKET_C2S_OUT_NAMEBRAND,	//
		PACKET_C2S_NAMEBRAND_LIST,	// 询问namebrand列表.
		PACKET_S2C_NAMEBRAND_LIST,	// 进入的玩家列表,分阶段发送，收到end代表发送完成.
		PACKET_S2C_NAMEBRAND_END,
		PACKET_S2C_NAMEBRAND_LIST_UP,	//新进来的玩家
		PACKET_S2C_NAMEBRAND_LIST_DOWN,	//离开的玩家
		PACKET_S2C_NAMEBRAND_BATTLE_STATUS,
		
		//BATTLE EXTRA.
		PACKET_S2C_ASKPK_TRANSMIT,	// 请求转发
		PACKET_C2S_ANSWER_TRANSMIT,	// 答复请求pk.[同步同意都发送BattlePKResult]
		PACKET_C2S_CREATE_ROOM,		//
		PACKET_S2C_CREATE_ROOM,
		PACKET_C2S_ENTER_ROOM,
		PACKET_S2C_ENTER_ROOM,
		PACKET_C2S_LEAVE_ROOM,
		PACKET_S2C_LEAVE_ROOM,

		//漂流瓶
		PACKET_C2S_THROW_DRIFT_BOTTLE,	//丢漂流瓶
		PACKET_S2C_THROW_DRIFT_RESULT,
		PACKET_C2S_PICK_DRIFT_BOTTLE,	//拾取漂流瓶
		PACKET_S2C_PICK_DRIFT_RESULT,
		PACKET_C2S_REMARK_DRIFT_BOTTLE,	//评论
		PACKET_S2C_REMARK_RESULT,

		//公会
		PACKET_C2S_CREATE_GUILD,
		PACKET_S2C_CREATE_GUILD,
		PACKET_C2S_ENTER_GUILD,
		PACKET_S2C_ENTER_GUILD,
		PACKET_C2S_LEAVE_GUILD,
		PACKET_S2C_LEAVE_GUILD,
		PACKET_S2C_GUILD_DISMISS,		//公会解散
		PACKET_C2S_GUILDS_LIST,
		PACKET_S2C_GUILDS_LIST,
		PACKET_S2C_GUILDS_LIST_END,
		PACKET_C2S_MEMBER_LIST,
		PACKET_S2C_MEMBER_LIST,
		PACKET_S2C_MEMBER_LIST_END,
		PACKET_C2S_GUILD_INFO,
		PACKET_S2C_GUILD_INFO,
		PACKET_S2C_MEMBER_EXP_CHANGE,
		PACKET_C2S_IN_GUILD_PK,		// 这里跟撕名牌里面可以整合，要不然管理起来是问题.
		PACKET_S2C_IN_GUILD_PK,
		PACKET_C2S_OUT_GUILD_PK,
		PACKET_S2C_OUT_GUILD_PK,
		PACKET_C2S_GUILD_CHANGE_INFO,
		PACKET_C2S_MEMBER_POWER,
		PACKET_C2S_APPLY_MEMBERS,
		PACKET_S2C_APPLY_MEMBERS,
		PACKET_C2S_GUILD_NOTIFY,
		PACKET_C2S_GUILD_KICK,
		PACKET_S2C_ADD_MEMBER,
		PACKET_S2C_DEL_MEMBER,
		PACKET_C2S_GUILD_UPGRADE,

		//activity.
		PACKET_C2S_ACTIVITY_LIST,
		PACKET_S2C_ACTIVITY_LIST,
		PACKET_C2S_ACTIVITY_DRAW,
		PACKET_S2C_ACTIVITY_DRAW,

		//chat, notify
		PACKET_C2S_NOTIFY_MSG,
		PACKET_S2C_NOTIFY_MSG,
		PACKET_C2S_CHAT,
		PACKET_S2C_CHAT,

		//activity..gong fang;
		PACKET_C2S_ENTER_GONGFANG,		//自己进入攻防界面
		PACKET_C2S_BEGIN_GONGFANG,		//开始攻击别人的请求
		PACKET_S2C_BEGIN_GONGFANG,
		PACKET_C2S_START_GONGFANG,		//开始攻防;
		PACKET_C2S_FINISH_GONGFANG,
		PACKET_S2C_FINISH_GONGFANG,		//攻防结束;
		PACKET_C2S_CHANGE_GONGFANG_TYPE,//修改攻防塔的类型
		PACKET_C2S_GONGFANG_INFO,
		PACKET_S2C_GONGFANG_INFO,
		PACKET_C2S_GONGFANG_ADD,		//扯淡的设计，必须客户端一个个添加吧;
		PACKET_C2S_GONGFANG_RECEIVE,		//
		PACKET_C2S_GONGFANG_BEGIN_UPGRADE,	//	通知开始升级倒计时
		PACKET_C2S_GONGFANG_UPGRADE,	//升级接口

		//单击游戏模式;
		PACKET_C2S_SINGLE_DATA,			//单击游戏数据保存,以及一些处理;

		//赠送体力;
		PACKET_C2S_ASK_VIGOR,
		PACKET_C2S_ASK_VIGOR_RESULT,

		PACKET_S2C_HAVE_NEWS,

		PACKET_SYNC_GUILD_DATA,
		PACKET_SYNC_GUILD_MEMBER_DATA,
		PACKET_C2S_CHANGE_GUILD_DESC,		//修改公会的简介
		PACKET_S2C_GUILD_DESC,
		PACKET_S2C_GUILD_NAME_HEAD_POS,		//.

		//////
		PACKET_C2S_ASK_GUILD_BOSS,			//请求进入公会战
		PACKET_S2C_RET_GUILD_BOSS,			//请求的返回
		PACKET_C2S_REPORT_GUILD_BOSS,
		PACKET_C2S_GUILD_BOSS_RANK,			//请求查看boss的排行榜信息;
		PACKET_S2C_GUILD_BOSS_RANK,			//回复给客户端boss的排行榜信息;
		PACKET_C2S_LEAVE_GUILD_BOSS,
		//////

		//guild复仇相关
		PACKET_C2S_ASK_GUILD_TARGET_OP,			//请求相关操作.1搜寻对手，2查询自己被打列表 3查询排行榜信息
		PACKET_S2C_ASK_GUILD_TARGET,			//返回对手信息
		PACKET_S2C_ASK_GUILD_BEATTACK_LIST,		//返回自己被打列表
		PACKET_S2C_ASK_GUILD_TARGET_RANK,		//返回排行榜信息
		PACKET_C2S_REPORT_GUILD_TARGET_RESULT,	//战斗完后报告结果
		PACKET_C2S_ASK_GUILD_TARGET_REVENGE,	//自己复仇目标;

		PACKET_C2S_ASK_JINKUANG,				//金矿
		PACKET_S2C_ASK_JINKUANG,				//..

		PACKET_C2S_CHANGE_ICON,					//change icon.
		PACKET_S2C_CARD_BAG,					//CARD BAG
		PACKET_C2S_ADD_CARD,					//+
		PACKET_C2S_REPLACE_CARD,				//REPLACE
		PACKET_C2S_SET_FIGHT_CARD,				//上场
		PACKET_C2S_SETTING_CARD,				//设置属性。

		PACKET_COUNT,
	};
}

#endif
